-- Ejecuta este archivo completo en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  max_accesses integer not null default 1 check (max_accesses between 1 and 999),
  used_accesses integer not null default 0 check (used_accesses >= 0),
  qr_color text not null default '#A855F7' check (qr_color ~ '^#[0-9A-Fa-f]{6}$'),
  token text unique not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  guest_id uuid references public.guests(id) on delete cascade,
  scanned_token text not null,
  status text not null check (status in ('granted','denied_exhausted','denied_inactive','denied_invalid')),
  ip text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists guests_token_idx on public.guests(token);
create index if not exists access_logs_guest_id_idx on public.access_logs(guest_id);
create index if not exists access_logs_created_at_idx on public.access_logs(created_at desc);

alter table public.guests enable row level security;
alter table public.access_logs enable row level security;

-- No creamos políticas públicas. El panel usa una Route API del servidor con la Service Role.

create or replace function public.redeem_qr_access(
  p_token text,
  p_ip text default null,
  p_user_agent text default null
)
returns table (
  status text,
  guest_id uuid,
  name text,
  max_accesses integer,
  used_accesses integer,
  remaining_accesses integer,
  qr_color text,
  active boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_guest public.guests%rowtype;
begin
  select * into v_guest
  from public.guests
  where token = p_token
  for update;

  if not found then
    insert into public.access_logs(guest_id, scanned_token, status, ip, user_agent)
    values (null, p_token, 'denied_invalid', p_ip, p_user_agent);

    return query select 'denied_invalid'::text, null::uuid, null::text, null::integer, null::integer, null::integer, null::text, null::boolean;
    return;
  end if;

  if not v_guest.active then
    insert into public.access_logs(guest_id, scanned_token, status, ip, user_agent)
    values (v_guest.id, p_token, 'denied_inactive', p_ip, p_user_agent);

    return query select 'denied_inactive'::text, v_guest.id, v_guest.name, v_guest.max_accesses, v_guest.used_accesses,
      greatest(v_guest.max_accesses - v_guest.used_accesses, 0), v_guest.qr_color, v_guest.active;
    return;
  end if;

  if v_guest.used_accesses >= v_guest.max_accesses then
    insert into public.access_logs(guest_id, scanned_token, status, ip, user_agent)
    values (v_guest.id, p_token, 'denied_exhausted', p_ip, p_user_agent);

    return query select 'denied_exhausted'::text, v_guest.id, v_guest.name, v_guest.max_accesses, v_guest.used_accesses, 0, v_guest.qr_color, v_guest.active;
    return;
  end if;

  update public.guests
  set used_accesses = used_accesses + 1,
      updated_at = now()
  where id = v_guest.id
  returning * into v_guest;

  insert into public.access_logs(guest_id, scanned_token, status, ip, user_agent)
  values (v_guest.id, p_token, 'granted', p_ip, p_user_agent);

  return query select 'granted'::text, v_guest.id, v_guest.name, v_guest.max_accesses, v_guest.used_accesses,
    greatest(v_guest.max_accesses - v_guest.used_accesses, 0), v_guest.qr_color, v_guest.active;
end;
$$;

revoke all on function public.redeem_qr_access(text,text,text) from public;
revoke all on function public.redeem_qr_access(text,text,text) from anon;
revoke all on function public.redeem_qr_access(text,text,text) from authenticated;
grant execute on function public.redeem_qr_access(text,text,text) to service_role;
